#docker-compose.yml
version: "3.8"

services:
  online-course-platform:
    image: moantarnouh/online-course-platform
    container_name: online-course-platform
    build:
      context: .
    command: ["npm", "run", "start:prod"]
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:13.1
    container_name: nestjs-database-connection-postgres-db
    restart: always
    environment:
      POSTGRES_USER: boghdady
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: online-courses-db
    volumes:
      - online-courses-db:/var/lib/postgresql/data
    ports:
      - 5434:5432

  adminer:
    image: adminer
    container_name: nestjs-database-connection-adminer
    restart: always
    ports: 
      - 8081:8080
    depends_on:
      - postgres

volumes:
  online-courses-db: